spring.application.name: spring-ai-demo-mcpserver

server.port: 8081

spring.ai.mcp.server:
  name: my-weather-server
  version: 0.0.1

spring.security.oauth2.resourceserver:
  opaquetoken:
    introspection-uri: http://localhost:9000/oauth2/introspect
    client-id: mcp-client
    client-secret: mcp-secret

logging.level.web: DEBUG
logging.level.org.springframework.security: TRACE